### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by BinEP** [Team-2502/RobotCode2017#2]
Consider changing to match previous years structure? com.team2502.robot2017
Also, command names. Having command in front of every command makes quick scanning difficult. Having CG in front of a command group makes sense because groups stand out. And reading through code is more difficult if a bunch of similar named things are near each other.

**Comment by vandench** [comment]
Package structure is correct, 'src/main/java/' is equivalent to 'src/'. The word 'Command' is always the same length, look left 7 characters when reading in the package structure and in classes don't mix modifiers which cause the class name to be offset. Also 'Cmd+f' on Mac or 'Ctrl+f' on Windows.
